[project]
name = "pyptv-env"
version = "0.1.0"
description = "Environment for running PyPTV"
authors = ["Claude <claude@anthropic.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
numpy = "1.23.*"
scipy = ">=1.15.2,<2"
matplotlib = ">=3.10.1,<4"
scikit-image = ">=0.25.0,<0.26"
pyyaml = ">=6.0.2,<7"
imagecodecs = ">=2024.12.30,<2025"
pillow = ">=11.1.0,<12"

[pypi-dependencies]
optv = ">=0.2.9, <0.3"
pyptv = { path = "/home/user/Documents/repos/pyptv/dist/pyptv-0.4.0-py3-none-any.whl" }
flowtracks = ">=1.0, <2"
tables = ">=3.10.2, <4"
pyside6 = "*"
